When checking of the journal is enabled, limit check to last 5 hours
When told to check the journal, logcheck was trying to check every single
entry, which is likely to cause logcheck to consume all the memory on the
system and be killed. This patch limits the first check to the most recent
5 hours worth of entries. (Subsequent runs are unchanged)

diff --git a/src/logcheck b/src/logcheck
--- a/src/logcheck
+++ b/src/logcheck
@@ -498,6 +498,12 @@ logoutput() {
 						offsettime=""
 						if [ -f "$offsetfile" ]; then
 								offsettime="--since=@$(stat -c %Y "$offsetfile")"
+						else
+								echo "This is the first time logcheck has checked the systemd journal." \
+										 >> "$TMPDIR/report" || error "Could not write message about first-time check of journal to report"
+								echo "Only recent entries (from the last 5 hours) will be checked" \
+										 >> "$TMPDIR/report" || error "Could not write message about first-time check of journal to report"
+								offsettime="--since=-5h"
 						fi
 						debug "Running $JOURNALCTL ${JOURNALCTL_OPTS[*]} -q $offsettime"
 						"$JOURNALCTL" "${JOURNALCTL_OPTS[@]}" --quiet "$offsettime" \
