More explicitly mention the default checking of the systemd journal

diff --git a/src/logcheck b/src/logcheck
--- a/src/logcheck
+++ b/src/logcheck
@@ -503,6 +503,8 @@ logoutput() {
 										 >> "$TMPDIR/report" || error "Could not write message about first-time check of journal to report"
 								echo "Only recent entries (from the last 5 hours) will be checked" \
 										 >> "$TMPDIR/report" || error "Could not write message about first-time check of journal to report"
+								echo "If you do not wish to check the systemd journal, please see /etc/logcheck/logcheck.logfiles.d/journal.logfiles" \
+										 >> "$TMPDIR/report" || error "Could not write message about first-time check of journal to report"
 								offsettime="--since=-5h"
 						fi
 						debug "Running $JOURNALCTL ${JOURNALCTL_OPTS[*]} -q $offsettime"
