Minor cleanups in greplogoutput and cleanrules
- Use mkdir -p to ensure dir for cleaned rules exists
- Skip the final filtering stages in greplogoutput if there is nothing to actually filter
- Replace the last use of 'ls' with globbing

diff --git a/src/logcheck b/src/logcheck
--- a/src/logcheck
+++ b/src/logcheck
@@ -229,12 +229,9 @@ cleanrules() {
 		local rulefile x
 		debug "cleanrules $dir => $cleaned"
 		if [ -d "$dir" ]; then
-				if [ ! -d "$cleaned" ]; then
-						mkdir "$cleaned" \
-								|| error "Could not make dir $cleaned for cleaned rulefiles."
-				fi
-				# run-parts doesn't include files which are not readable. Use this
-				# separate check to correctly report unreadable files.
+				mkdir -p "$cleaned" \
+								|| error "Could not make dir $cleaned (for cleaned rulefiles from $dir)"
+				# report unreadable files - run-parts silently discards them
 				for x in "$dir"/*; do
 						if [ -f "$x" ] && [ ! -r "$x" ]; then
 								error "Could not read $x"
@@ -349,7 +346,7 @@ sendreport() {
 #   $1 - directory of positive rules: any matches are added to the report
 #   $2 - heading for matches
 #   $3 - (optional) directory of ignore rules: filters out matches
-#   $4 - (optional) directory of ignorehigher rules: ??
+#   $4 - (optional) directory of ignorehigher rules: filters out matches
 greplogoutput() {
 		local raise="$1"
 		local sectionstring="$2"
@@ -395,18 +392,23 @@ greplogoutput() {
 										# Ignore files _always_ impact matches from logcheck
 										debug "Filtering entries using all rules in: $ignore (if it is set)"
 										for file in "$ignore"/* ; do
-												debug "clean logcheck-<package>: $file"
-												cleanchecked "$ignore"
+												if [ -s "$TMPDIR/checked" ]; then
+														cleanchecked "$ignore"
+												fi
 										done
 								else
 										debug "(It is not set)"
 								fi
 
-								debug "Cleaning logcheck"
-								# Remove any entries already reported
-								for file in $(ls -1 "$raise" | grep -v '^logcheck') ; do
-										debug "Cleaning logcheck: $file"
-										cleanchecked "$raise/$file"
+								# Remove any entries already reported under a separate section
+								debug "Filtering using any file in $raise that does not start with 'logcheck'"
+								for file in "$raise"/*; do
+										if [ -s "$TMPDIR/checked" ]; then
+												if ! [[ "$(basename "$file")" =~ ^logcheck* ]]; then
+													 debug "Filtering using: $file"
+													 cleanchecked "$file"
+												fi
+										fi
 								done
 						fi
 
@@ -429,7 +431,9 @@ greplogoutput() {
 								# Now apply any local-* files
 								debug "Filtering using: $ignore/local-*"
 								for file in "$ignore"/local-* ; do
-										cleanchecked "$file"
+										if [ -f "$file" ] && [ -s "$TMPDIR/checked" ]; then
+												cleanchecked "$file"
+										fi
 								done
 						fi
 
